// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package scan

import (
	context "context"
	wire "github.com/google/go-cloud/wire"
)

// Injectors from inject.go:

func SetupParallelScanner(ctx context.Context, tableName TableName, parallelScanWorkers ParallelScanWorkers, scanItemLimit ScanItemLimit) *ParallelScan {
	session := Session()
	dynamoDBAPI := Dynamodb(session)
	logger := Logger()
	parallelScan := New(dynamoDBAPI, tableName, parallelScanWorkers, scanItemLimit, logger)
	return parallelScan
}

// inject.go:

var parallelScannerSet = wire.NewSet(New, Dynamodb, Session, Logger)
